# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='sib_order',
            field=models.PositiveIntegerField(default=1),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='node',
            name='test_field',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
